"""Manim runtime for talk videos: slide pages timed to narration.

scene.py (generated by scripts/to_manim.py) subclasses TalkScene. Timing uses
the same timings.json as generate-explainer-video's ExplainerScene: one
scene per frame, a caption per sentence, windows that tile the timeline. So
begin(), at(), finish(), hold_until() and budget() behave the same, and the
timeline can come from real Kokoro narration (synthesize.py) or from the
word-count estimate to_manim.py writes when there is no audio.

Each frame is its rendered slide pages (PNG). show_frame() fades the frame in
and reveals each overlay step on a spoken sentence. A talk can replace the
default for any frame with a native Manim animation: put
talks/<slug>/manim/<label>.py (the frame's label=, else its id) defining
animate(scene, frame); it runs inside the frame's window.

Environment (set by to_manim.py): TALK_VIDEO_DIR (the build/video folder),
TALK_THEME (light or dark), TALK_CAPTIONS (1 or 0), TALK_OVERRIDES (folder).
"""
import importlib.util
import json
import os
import textwrap
from pathlib import Path

import manimpango
from manim import DOWN, UP, FadeIn, FadeOut, ImageMobject, RoundedRectangle, Scene, Text, VGroup, config

VIDEO = Path(os.environ.get("TALK_VIDEO_DIR", "."))
THEME = os.environ.get("TALK_THEME", "dark")
MANIFEST = json.loads((VIDEO / "manifest.json").read_text(encoding="utf-8"))
PALETTE = MANIFEST["palette"][THEME]
SERIF_CHOICES = ["P052", "TeX Gyre Pagella", "Palatino", "Palatino Linotype", "URW Palladio L",
                 "Liberation Serif", "DejaVu Serif"]
_installed = set(manimpango.list_fonts())
FONT = next((f for f in SERIF_CHOICES if f in _installed), "")

# The slide fills the top of the frame; the band below holds captions.
SLIDE_SCALE = 0.86
CAPTION_SIZE = 24
CAPTION_WRAP = 84
CAPTION_TAIL = 0.15
FADE = 0.5
STEP_FADE = 0.35

config.background_color = PALETTE["background"]


def text(s, size=28, color=None, **kw):
    """Text in the talk's serif and palette."""
    return Text(s, font=FONT, font_size=size, color=color or PALETTE["foreground"], **kw)


class TalkScene(Scene):
    def setup(self):
        self.timings = json.loads((VIDEO / "timings.json").read_text(encoding="utf-8"))
        self.by_id = {s["id"]: s for s in self.timings["scenes"]}
        self.current = None
        self.slide = None  # the ImageMobject on screen
        if os.environ.get("TALK_CAPTIONS", "1") != "0":
            self._start_captions()

    # ---------------------------------------------------------------- timing
    @property
    def now(self):
        return self.renderer.time

    def hold_until(self, seconds):
        remaining = seconds - self.now
        if remaining > 1 / self.camera.frame_rate:
            self.wait(remaining)

    def budget(self, seconds):
        return max(seconds - self.now, 1 / self.camera.frame_rate)

    def begin(self, frame_id):
        self.hold_until(self.by_id[frame_id]["window_start"])
        self.current = self.by_id[frame_id]
        return self.current

    def span(self, sentence):
        caps = self.current["captions"]
        entry = caps[min(sentence, len(caps) - 1)]
        return entry["start"], entry["end"]

    def at(self, sentence, fraction=0.0):
        start, end = self.span(sentence)
        self.hold_until(start + fraction * (end - start))

    def finish(self):
        self.hold_until(self.current["window_end"])

    # ---------------------------------------------------------------- slides
    def page(self, number):
        img = ImageMobject(str(VIDEO / "slides" / THEME / f"{number:03d}.png"))
        img.height = config.frame_height * SLIDE_SCALE
        img.to_edge(UP, buff=0.12)
        return img

    def swap_to(self, mob, run_time=FADE):
        """Cross-fade whatever is on screen (except captions) to ``mob``."""
        gone = [m for m in self.mobjects if getattr(m, "z_index", 0) < 100]
        anims = [FadeOut(m) for m in gone] + [FadeIn(mob)]
        self.play(*anims, run_time=min(run_time, self.budget(self.current["window_end"])))
        self.slide = mob

    def reveal_step(self, number):
        new = self.page(number)
        self.play(FadeIn(new), run_time=min(STEP_FADE, self.budget(self.current["window_end"])))
        if self.slide is not None:
            self.remove(self.slide)
        self.slide = new

    def show_frame(self, frame):
        """Default: fade the frame in, reveal overlay steps on sentences, hold."""
        self.begin(frame["id"])
        override = self._override(frame)
        if override:
            override(self, frame)
            self.finish()
            return
        pages = frame["pages"]
        self.swap_to(self.page(pages[0]))
        n_sent, n_steps = len(self.current["captions"]), len(pages)
        for j, number in enumerate(pages[1:], start=1):
            if n_sent >= n_steps:
                self.at(round(j * n_sent / n_steps))
            else:
                start, end = self.current["window_start"], self.current["window_end"]
                self.hold_until(start + j / n_steps * (end - start))
            self.reveal_step(number)
        self.finish()

    def _override(self, frame):
        folder = os.environ.get("TALK_OVERRIDES")
        if not folder:
            return None
        for name in filter(None, (frame.get("label"), frame["id"])):
            path = Path(folder) / f"{name}.py"
            if path.is_file():
                spec = importlib.util.spec_from_file_location(f"talk_override_{name.replace('-', '_')}", path)
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                return module.animate
        return None

    # ---------------------------------------------------------------- captions
    def _start_captions(self):
        entries = [c for s in self.timings["scenes"] for c in s["captions"]]
        # Build every caption once and toggle opacity from the clock: Manim fixes
        # the redraw list at the start of each play()/wait(), so swapping text
        # mid-call would leave ghosts (the same fix as ExplainerScene).
        boxes = [self._caption_box(c["text"]) for c in entries]
        holder = VGroup(*[VGroup(panel, label) for panel, label in boxes])

        def refresh(_, dt):
            t = self.now
            active = next((k for k, c in enumerate(entries)
                           if c["start"] - 0.05 <= t < c["end"] + CAPTION_TAIL), None)
            for k, (panel, label) in enumerate(boxes):
                shown = 1.0 if k == active else 0.0
                panel.set_fill(PALETTE["caption_bg"], opacity=0.86 * shown)
                label.set_opacity(shown)

        refresh(None, 0)
        holder.add_updater(refresh)
        holder.set_z_index(100)
        for m in holder.submobjects:
            m.set_z_index(100)
        self.add(holder)

    def _caption_box(self, s):
        label = text(textwrap.fill(s, CAPTION_WRAP), CAPTION_SIZE, PALETTE["caption_fg"], line_spacing=0.9)
        limit = config.frame_width - 1.0
        if label.width > limit:
            label.scale_to_fit_width(limit)
        panel = RoundedRectangle(corner_radius=0.1, width=label.width + 0.6, height=label.height + 0.3,
                                 fill_color=PALETTE["caption_bg"], fill_opacity=0.86, stroke_width=0)
        label.move_to(panel)
        VGroup(panel, label).to_edge(DOWN, buff=0.12)
        return panel, label
