#!/usr/bin/env python3
"""Turn design-tokens.json into tex/yjtokens.tex, the colours every talk uses.

design-tokens.json is a snapshot of the visuals repo's token file, so slides
and web visualizations share one palette. `--sync DIR` refreshes the snapshot
from a visuals checkout first; `--verify` checks the generated file is current
and writes nothing.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "design-tokens.json"
OUT = ROOT / "tex" / "yjtokens.tex"

# Token name -> LaTeX colour name. Order is fixed so output is byte-stable.
COLOURS = [
    ("background", "yjBackground"),
    ("foreground", "yjForeground"),
    ("secondary", "yjSecondary"),
    ("surface", "yjSurface"),
    ("border", "yjBorder"),
    ("focus", "yjFocus"),
    ("mark", "yjMark"),
    ("selected", "yjSelected"),
]


def render(tokens):
    colors = tokens["colors"]
    lines = [
        "% Generated by scripts/sync_tokens.py from design-tokens.json. Do not edit.",
        "% Change design-tokens.json (or --sync it from visuals) and regenerate.",
    ]
    for key, name in COLOURS:
        value = colors[key].lstrip("#").upper()
        if len(value) != 6:
            sys.exit(f"token colors.{key} is not a #RRGGBB colour: {colors[key]}")
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{value}}}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sync", metavar="VISUALS_DIR", help="copy design-tokens.json from a visuals checkout first")
    ap.add_argument("--verify", action="store_true", help="check tex/yjtokens.tex is current; write nothing")
    args = ap.parse_args()

    if args.sync:
        src = Path(args.sync) / "design-tokens.json"
        if not src.is_file():
            sys.exit(f"no design-tokens.json in {args.sync}")
        shutil.copyfile(src, TOKENS)
        print(f"synced {TOKENS.name} from visuals")

    text = render(json.loads(TOKENS.read_text()))
    if args.verify:
        if not OUT.is_file() or OUT.read_text() != text:
            sys.exit("tex/yjtokens.tex is stale: run python3 scripts/sync_tokens.py")
        print("verified: tex/yjtokens.tex matches design-tokens.json")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
