#!/usr/bin/env python3
"""Turn theme-tokens.json into tex/yjtokens.tex, the colours every talk uses.

theme-tokens.json has a `light` and a `dark` palette with the same keys. The
generated file defines yjL<Name> and yjD<Name> for every key, plus
\\yjusepalette{L|D}, which points the working names (yjBackground, yjAccent,
...) at one palette. yjtalk.sty calls it with D for the dark variant.
`--verify` checks the generated file is current and writes nothing.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "theme-tokens.json"
OUT = ROOT / "tex" / "yjtokens.tex"
MODES = {"light": "L", "dark": "D"}


def tex_name(key):
    return "".join(part.capitalize() for part in key.split("_"))


def render(tokens):
    keys = list(tokens["light"])
    if list(tokens["dark"]) != keys:
        sys.exit("theme-tokens.json: light and dark must list the same keys in the same order")
    lines = [
        "% Generated by scripts/sync_tokens.py from theme-tokens.json. Do not edit.",
        "% Change theme-tokens.json and regenerate.",
    ]
    for mode, letter in MODES.items():
        for key in keys:
            value = tokens[mode][key]
            if not re.fullmatch(r"#[0-9A-Fa-f]{6}", value):
                sys.exit(f"theme-tokens.json: {mode}.{key} is not a #RRGGBB colour: {value}")
            lines.append(f"\\definecolor{{yj{letter}{tex_name(key)}}}{{HTML}}{{{value[1:].upper()}}}")
    lines.append("\\newcommand{\\yjusepalette}[1]{%")
    lines += [f"  \\colorlet{{yj{tex_name(k)}}}{{yj#1{tex_name(k)}}}%" for k in keys]
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verify", action="store_true", help="check tex/yjtokens.tex is current; write nothing")
    args = ap.parse_args()
    text = render(json.loads(TOKENS.read_text()))
    if args.verify:
        if not OUT.is_file() or OUT.read_text() != text:
            sys.exit("tex/yjtokens.tex is stale: run python3 scripts/sync_tokens.py")
        print("verified: tex/yjtokens.tex matches theme-tokens.json")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
