#!/usr/bin/env python3
"""Turn a built talk into a narrated Manim video, one scene per frame.

    python3 scripts/to_manim.py <slug>                  # estimate timing, render silent 480p
    python3 scripts/to_manim.py <slug> --quality m      # 720p30 (h: 1080p60)
    python3 scripts/to_manim.py <slug> --prepare-only   # write inputs, do not render

Writes talks/<slug>/build/video/:

  script.json    generate-explainer-video's script format: one scene per
                 frame, narration from \\narration (section dividers say
                 "Part N. <title>."; a frame without narration says its title)
  timings.json   the timeline scene.py follows (see below)
  manifest.json  frames, their pages, labels and the palette
  slides/<theme>/NNN.png  every slide page at 1920x1080
  scene.py       generated; subclasses manim/talkscene.py
  <slug>.mp4     the video; captions.srt beside it

Timing. With real narration, run generate-explainer-video's synthesize.py on
script.json (it writes into this folder by default); it writes narration.wav
and timings.json from Kokoro in the script's voice, British English bf_emma
unless --voice says otherwise. This script then keeps that timeline and muxes the
audio. Without it, timings come from word counts at 130 words a minute, with
the explainer's lead, gap and tail, and the video is silent: good for checking
pacing and visuals before any speech exists.

The default visual for a frame is its slide pages: fade in, then one overlay
step per spoken sentence. talks/<slug>/manim/<label or id>.py can replace any
frame with a native animation (see manim/talkscene.py).
"""
import argparse
import datetime
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from talk_manifest import ROOT, TALKS, WORDS_PER_MINUTE, build_manifest, sentences  # noqa: E402

TOKENS = ROOT / "theme-tokens.json"
RUNTIME = ROOT / "manim"
LEAD, GAP, TAIL = 0.5, 0.7, 1.5  # seconds, as in generate-explainer-video
QUALITY_DIR = {"l": "480p15", "m": "720p30", "h": "1080p60"}
# British English by default. Kokoro voice ids start with their language
# (a American, b British); generate-explainer-video's synthesize.py builds the
# matching pipeline from that letter.
DEFAULT_VOICE = "bf_emma"

SCENE_PY = '''"""Generated by scripts/to_manim.py. Do not edit: change talk.tex, or add
talks/<slug>/manim/<label>.py for a native animation of one frame."""
import os
import sys

sys.path.insert(0, os.environ["TALK_RUNTIME"])
from talkscene import MANIFEST, TalkScene  # noqa: E402


class Talk(TalkScene):
    def construct(self):
        for frame in MANIFEST["frames"]:
            self.show_frame(frame)
'''


def fail(msg):
    sys.exit(f"to_manim: {msg}")


def run(cmd, **kw):
    print("+", " ".join(str(c) for c in cmd), flush=True)
    subprocess.run(cmd, check=True, **kw)


def narration_for(frame):
    if frame["narration"]:
        return frame["narration"], True
    if frame["kind"] == "section":
        return f"Part {frame['section_number']}. {frame['title']}.", True
    return frame["title"].rstrip(".") + ".", False


def iso_date(text):
    for fmt in ("%d %B %Y", "%B %d, %Y", "%Y-%m-%d", "%d %b %Y"):
        try:
            return datetime.datetime.strptime(text.strip(), fmt).date().isoformat()
        except ValueError:
            pass
    return ""


def palette(tokens):
    def one(p, caption_bg, caption_fg):
        return {"background": p["background"], "foreground": p["foreground"], "secondary": p["secondary"],
                "accent": p["accent"], "accent_text": p["accent_text"], "warm": p["warm"],
                "border": p["border"], "caption_bg": caption_bg, "caption_fg": caption_fg}
    light, dark = tokens["light"], tokens["dark"]
    return {"light": one(light, light["foreground"], light["background"]),
            "dark": one(dark, "#07101C", dark["foreground"])}


def estimate_timings(script):
    """The explainer's timeline shape, from word counts instead of audio."""
    clock, scenes = LEAD, []
    for k, scene in enumerate(script["scenes"]):
        start, captions = clock, []
        for s in sentences(scene["narration"]):
            d = max(1.2, len(s.split()) / WORDS_PER_MINUTE * 60)
            captions.append({"start": round(clock, 3), "end": round(clock + d, 3), "text": s})
            clock += d
        scenes.append({"id": scene["id"], "title": scene["title"], "audio_start": round(start, 3),
                       "audio_end": round(clock, 3), "captions": captions})
        if k < len(script["scenes"]) - 1:
            clock += GAP
    total = clock + TAIL
    for k, s in enumerate(scenes):
        s["window_start"] = 0.0 if k == 0 else scenes[k - 1]["window_end"]
        s["window_end"] = round(scenes[k + 1]["audio_start"] if k + 1 < len(scenes) else total, 3)
    return {"voice": "estimate", "speed": 1.0, "words_per_minute": WORDS_PER_MINUTE,
            "total_seconds": round(total, 3), "scenes": scenes}


def srt(timings):
    def t(x):
        ms = round(x * 1000)
        h, ms = divmod(ms, 3_600_000)
        m, ms = divmod(ms, 60_000)
        s, ms = divmod(ms, 1000)
        return f"{h:02}:{m:02}:{s:02},{ms:03}"
    lines, n = [], 1
    for scene in timings["scenes"]:
        for c in scene["captions"]:
            lines += [str(n), f"{t(c['start'])} --> {t(c['end'])}", c["text"], ""]
            n += 1
    return "\n".join(lines)


def prepare(slug, theme, voice):
    manifest = build_manifest(slug)
    talk_dir = TALKS / slug
    pdf = talk_dir / "build" / ("talk-dark.pdf" if theme == "dark" else "talk-slides.pdf")
    if not pdf.is_file():
        fail(f"{pdf.relative_to(ROOT)} missing: python3 scripts/build.py {slug} --only slides,dark")
    out = talk_dir / "build" / "video"
    out.mkdir(parents=True, exist_ok=True)

    slides = out / "slides" / theme
    if slides.exists():
        shutil.rmtree(slides)
    slides.mkdir(parents=True)
    for page in range(1, manifest["pages"] + 1):
        subprocess.run(["pdftoppm", "-png", "-singlefile", "-f", str(page), "-l", str(page),
                        "-scale-to-x", "1920", "-scale-to-y", "1080", str(pdf), str(slides / f"{page:03d}")], check=True)

    missing, scenes = [], []
    for f in manifest["frames"]:
        text, written = narration_for(f)
        if not written:
            missing.append(f["id"])
        scenes.append({"id": f["id"], "title": f["title"], "narration": text})
    date = iso_date(manifest["date"])
    script = {
        "id": f"{date}-{slug}" if date else slug,
        "title": manifest["title"], "summary": manifest["subtitle"] or manifest["title"],
        "date": date, "focus_tags": [], "voice": voice, "speed": 1.0,
        "sources": [f"talks/{slug}/talk.tex"], "scenes": scenes,
    }
    (out / "script.json").write_text(json.dumps(script, indent=2, ensure_ascii=False) + "\n")
    (out / "manifest.json").write_text(json.dumps({
        "slug": slug, "title": manifest["title"],
        "frames": [{k: f[k] for k in ("id", "label", "kind", "title", "pages")} for f in manifest["frames"]],
        "palette": palette(json.loads(TOKENS.read_text())),
    }, indent=2, ensure_ascii=False) + "\n")
    (out / "scene.py").write_text(SCENE_PY)
    if missing:
        print(f"note: no \\narration on {len(missing)} frame(s), the video speaks their title: {', '.join(missing)}")
    return out, script


def choose_timings(out, script):
    """Keep Kokoro timings if they match this script; else write an estimate."""
    path, audio = out / "timings.json", out / "narration.wav"
    if path.is_file() and audio.is_file():
        timings = json.loads(path.read_text())
        same_ids = [s["id"] for s in timings["scenes"]] == [s["id"] for s in script["scenes"]]
        same_text = all(" ".join(c["text"] for c in t["captions"]).split() == s["narration"].split()
                        for t, s in zip(timings["scenes"], script["scenes"], strict=False))
        same_voice = timings.get("voice") == script["voice"]
        if timings.get("voice") != "estimate" and same_ids and same_text and same_voice:
            print(f"timing: Kokoro narration ({timings['voice']}), {timings['total_seconds']:.1f}s")
            return timings, audio
        print(f"timing: narration.wav ({timings.get('voice')}) is stale for this script ({script['voice']}); using the word-count estimate "
              "(rerun synthesize.py to refresh it)")
    timings = estimate_timings(script)
    path.write_text(json.dumps(timings, indent=2, ensure_ascii=False) + "\n")
    print(f"timing: estimate at {WORDS_PER_MINUTE} wpm, {timings['total_seconds']:.1f}s, silent")
    return timings, None


def ass_colour(hex_colour, alpha=0):
    r, g, b = hex_colour[1:3], hex_colour[3:5], hex_colour[5:7]
    return f"&H{alpha:02X}{b}{g}{r}".upper()


def ass(timings, pal, font):
    """ASS subtitles styled like the talk: serif, a box in the caption colours."""
    def t(x):
        cs = round(x * 100)
        h, cs = divmod(cs, 360000)
        m, cs = divmod(cs, 6000)
        s, cs = divmod(cs, 100)
        return f"{h}:{m:02}:{s:02}.{cs:02}"
    head = f"""[Script Info]
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,{font},42,{ass_colour(pal['caption_fg'])},{ass_colour(pal['caption_fg'])},{ass_colour(pal['caption_bg'], 0x30)},{ass_colour(pal['caption_bg'], 0x30)},0,0,0,0,100,100,0,0,3,14,0,2,120,120,26,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    lines = [f"Dialogue: 0,{t(c['start'])},{t(c['end'] + 0.15)},Caption,,0,0,0,,{c['text']}"
             for scene in timings["scenes"] for c in scene["captions"]]
    return head + "\n".join(lines) + "\n"


def has_libass():
    out = subprocess.run(["ffmpeg", "-hide_banner", "-filters"], capture_output=True, text=True).stdout
    return re.search(r"\bsubtitles\b", out) is not None


def render(slug, out, timings, audio, quality, theme, captions, python):
    # Burned-in captions (libass) keep Manim's frames static between reveals,
    # which renders several times faster than drawing captions in Manim.
    burn = captions and has_libass()
    env = dict(os.environ, TALK_VIDEO_DIR=str(out), TALK_THEME=theme, TALK_RUNTIME=str(RUNTIME),
               TALK_CAPTIONS="1" if captions and not burn else "0", TALK_OVERRIDES=str(TALKS / slug / "manim"))
    media = out / "media"
    run([python, "-m", "manim", "render", f"-q{quality}", "--media_dir", str(media), "--format", "mp4",
         "--disable_caching", "--progress_bar", "none", "-v", "WARNING",
         str(out / "scene.py"), "Talk"], env=env, cwd=out)
    silent = media / "videos" / "scene" / QUALITY_DIR[quality] / "Talk.mp4"
    video = out / f"{slug}.mp4"
    total = f"{timings['total_seconds']:.3f}"
    (out / "captions.srt").write_text(srt(timings))
    vf = []
    if burn:
        pal = json.loads((out / "manifest.json").read_text())["palette"][theme]
        font = subprocess.run([python, "-c", "import sys; sys.path.insert(0, sys.argv[1]); import os; "
                               "os.environ['TALK_VIDEO_DIR']=sys.argv[2]; from talkscene import FONT; print(FONT)",
                               str(RUNTIME), str(out)], capture_output=True, text=True).stdout.strip() or "serif"
        (out / "captions.ass").write_text(ass(timings, pal, font))
        vf = ["-vf", "subtitles=captions.ass"]
    cmd = ["ffmpeg", "-y", "-loglevel", "error", "-i", str(silent)]
    if audio:
        cmd += ["-i", str(audio), "-map", "0:v:0", "-map", "1:a:0", "-c:a", "aac", "-b:a", "160k"]
    cmd += vf + ["-c:v", "libx264", "-preset", "medium", "-crf", "20", "-pix_fmt", "yuv420p",
                 "-t", total, "-movflags", "+faststart", video.name]
    run(cmd, cwd=out)
    return video


def check(out, video, timings, frames_dir):
    seconds = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0",
                                    str(video)], capture_output=True, text=True, check=True).stdout)
    expected = timings["total_seconds"]
    if abs(seconds - expected) > 0.6:
        fail(f"{video.name} is {seconds:.2f}s, timeline says {expected:.2f}s")
    if frames_dir:
        if frames_dir.exists():
            shutil.rmtree(frames_dir)
        frames_dir.mkdir(parents=True)
        for s in timings["scenes"]:
            at = (s["window_start"] + s["window_end"]) / 2 if s["captions"] else s["window_start"] + 0.5
            if s["captions"]:
                at = max(at, s["captions"][-1]["end"] - 0.2)  # after the last reveal of the frame
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-ss", f"{at:.2f}", "-i", str(video), "-frames:v", "1",
                            str(frames_dir / f"{s['id']}.png")], check=True)
    print(f"verified: {video.relative_to(ROOT)} {seconds:.1f}s matches the timeline "
          f"({len(timings['scenes'])} scenes){'; review frames in ' + str(frames_dir.relative_to(ROOT)) if frames_dir else ''}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("slug")
    ap.add_argument("--theme", choices=["dark", "light"], default="dark")
    ap.add_argument("--voice", default=DEFAULT_VOICE,
                    help=f"Kokoro voice id written to script.json (default {DEFAULT_VOICE}, British English; "
                         "bm_george for a British male voice, af_heart for American)")
    ap.add_argument("--quality", choices=sorted(QUALITY_DIR), default="l")
    ap.add_argument("--no-captions", action="store_true")
    ap.add_argument("--prepare-only", action="store_true", help="write script, slides and scene; do not render")
    ap.add_argument("--python", default=os.environ.get("MANIM_PYTHON", sys.executable),
                    help="interpreter that has manim installed (default: this one, or $MANIM_PYTHON)")
    args = ap.parse_args()

    if not re.fullmatch(r"[abefhijpz][fm]_[a-z]+", args.voice):
        fail(f"{args.voice!r} is not a Kokoro voice id (e.g. bf_emma, bm_george, af_heart)")
    out, script = prepare(args.slug, args.theme, args.voice)
    timings, audio = choose_timings(out, script)
    if args.prepare_only:
        subprocess.run([sys.executable, "-m", "py_compile", str(out / "scene.py")], check=True)
        print(f"prepared {out.relative_to(ROOT)}: {len(script['scenes'])} scenes, {timings['total_seconds']:.1f}s")
        return
    if subprocess.run([args.python, "-c", "import manim"], capture_output=True).returncode:
        fail(f"{args.python} cannot import manim; pass --python or set MANIM_PYTHON to a venv with manim")
    if not shutil.which("ffmpeg"):
        fail("ffmpeg not found")
    video = render(args.slug, out, timings, audio, args.quality, args.theme, not args.no_captions, args.python)
    check(out, video, timings, out / "frames")


if __name__ == "__main__":
    main()
