#!/usr/bin/env python3
"""Build a talk into an interactive web deck: static HTML, JavaScript and SVG.

    python3 scripts/to_web.py <slug>            # write talks/<slug>/build/web/
    python3 scripts/to_web.py <slug> --check    # verify an existing build, write nothing

Every slide page of talk-slides.pdf and talk-dark.pdf becomes an SVG
(pdftocairo), so any frame the PDF can show, the web deck shows identically:
overlays are steps, and the viewer switches light and dark. web/shell.html
supplies the runtime, modelled on generate-slide-deck's deck shell: arrow keys
and swipe, #n deep links, an overview with search (O, /), a transcript of
\\narration (C), the talk's CSV data with download (D), fullscreen (F), and a
presenter window (P) with notes, next slide and clock, kept in sync over a
BroadcastChannel. Read-only WebMCP tools expose metadata, slide text, search
and data; never the speaker notes.

Speaker notes go to notes.md beside index.html in presentation-coach's
format (one `## <slide-id>` section per slide). They load only when the
folder is served over HTTP and appear only in the presenter window; publish
the folder without notes.md to keep them private.

Output is deterministic: the same PDFs give the same bytes.
"""
import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from talk_manifest import ROOT, TALKS, build_manifest  # noqa: E402

SHELL = ROOT / "web" / "shell.html"
TOKENS = ROOT / "theme-tokens.json"
WORDS_PER_MINUTE = 130  # same budget as generate-explainer-video
MAX_DECK_BYTES = 40_000_000


def fail(msg):
    sys.exit(f"to_web: {msg}")


def shade(hex_colour, factor):
    """Darken (factor < 1) or lighten towards white (factor > 1) a #RRGGBB colour."""
    r, g, b = (int(hex_colour[i:i + 2], 16) for i in (1, 3, 5))
    if factor <= 1:
        r, g, b = (round(c * factor) for c in (r, g, b))
    else:
        t = factor - 1
        r, g, b = (round(c + (255 - c) * t) for c in (r, g, b))
    return f"#{r:02X}{g:02X}{b:02X}"


def theme_css(tokens):
    def block(p, chrome):
        pairs = {"bg": p["background"], "surface": p["surface"], "fg": p["foreground"],
                 "secondary": p["secondary"], "border": p["border"], "accent": p["accent"],
                 "accent-text": p["accent_text"], "chrome": chrome}
        return ";".join(f"--{k}:{v}" for k, v in pairs.items())
    light, dark = tokens["light"], tokens["dark"]
    return (f":root{{{block(light, light['surface'])};color-scheme:light}}\n"
            f":root[data-theme=dark]{{{block(dark, shade(dark['background'], 0.7))};color-scheme:dark}}")


def seconds_for(text):
    words = len(text.split())
    return round(words / WORDS_PER_MINUTE * 60) + 2 if words else 3


def mmss(seconds):
    return f"{seconds // 60}:{seconds % 60:02d}"


def sentences(text):
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]


def notes_markdown(manifest):
    """presentation-coach notes.md from \\note text; cues are split into fields."""
    total = sum(seconds_for(f["narration"]) for f in manifest["frames"])
    out = [f"# Speaker notes: {manifest['title']}", "", "## deck",
           f"**Takeaway:** {manifest['subtitle'] or manifest['title']}",
           f"**Total time:** {mmss(total)}",
           "**Source:** generated by scripts/to_web.py from the \\note text in talk.tex; edit talk.tex, not this file.",
           ""]
    for f in manifest["frames"]:
        out.append(f"## {f['id']}")
        if f["narration"]:
            out.append(f"**Time:** {mmss(seconds_for(f['narration']))}")
        if f["kind"] == "section":
            out += [f"**Say:** Section {f['section_number']}: {f['title']}. Pause; say in one sentence what this part answers.", ""]
            continue
        if len(f["notes"]) > 1:  # \note[item]{...} cues
            out.append("**Cues:**")
            out += [f"- {n}" for n in f["notes"]]
            out.append("")
            continue
        text = " ".join(f["notes"])
        fields, questions = {}, []
        for m in re.finditer(r"Likely question:\s*(.*?)(?:\s*Answer:\s*(.*?))?(?=\s*(?:Transition:|Likely question:|$))", text, re.S):
            questions.append(m.group(1).strip() + (f" {m.group(2).strip()}" if m.group(2) else ""))
        text = re.sub(r"Likely question:.*?(?=\s*(?:Transition:|$))", "", text, flags=re.S)
        m = re.search(r"Transition:\s*(.*)$", text, re.S)
        if m:
            fields["Transition"] = m.group(1).strip()
            text = text[:m.start()].strip()
        said = sentences(text)
        if said:
            out.append(f"**Emphasise:** {said[0]}")
        if len(said) > 1:
            out.append(f"**Say:** {' '.join(said[1:])}")
        if "Transition" in fields:
            out.append(f"**Transition:** {fields['Transition']}")
        if questions:
            out.append("**Likely questions:**")
            out += [f"- {q}" for q in questions]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_svgs(pdf, dest, pages):
    dest.mkdir(parents=True, exist_ok=True)
    for page in range(1, pages + 1):
        out = dest / f"{page:03d}.svg"
        subprocess.run(["pdftocairo", "-svg", "-f", str(page), "-l", str(page), str(pdf), str(out)], check=True)


def build(slug):
    if not shutil.which("pdftocairo"):
        fail("pdftocairo not found; install poppler-utils")
    manifest = build_manifest(slug)
    talk_dir = TALKS / slug
    build_dir = talk_dir / "build"
    out = build_dir / "web"
    if out.exists():
        shutil.rmtree(out)
    themes = []
    for theme, pdf in (("light", build_dir / "talk-slides.pdf"), ("dark", build_dir / "talk-dark.pdf")):
        if pdf.is_file():
            render_svgs(pdf, out / "slides" / theme, manifest["pages"])
            themes.append(theme)
    if "light" not in themes:
        fail("talk-slides.pdf missing: python3 scripts/build.py <slug> --only slides,dark")

    data = [{"path": d["path"], "csv": (talk_dir / d["path"]).read_text()} for d in manifest["data"]]
    public = {k: manifest[k] for k in ("slug", "title", "subtitle", "author", "date", "institute")}
    public["themes"] = themes
    public["frames"] = [{k: f[k] for k in ("n", "id", "kind", "title", "section", "pages", "text", "narration", "source")}
                        for f in manifest["frames"]]
    public["data"] = data
    data_json = json.dumps(public, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

    html = SHELL.read_text()
    description = manifest["subtitle"] or manifest["title"]
    esc = lambda s: s.replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")
    for key, value in {"TITLE": esc(manifest["title"]), "DESCRIPTION": esc(description),
                       "THEME_CSS": theme_css(json.loads(TOKENS.read_text()))}.items():
        html = html.replace("{{" + key + "}}", value)
    html = html.replace("{{DATA_JSON}}", data_json)
    (out / "index.html").write_text(html)
    (out / "notes.md").write_text(notes_markdown(manifest))
    return out, manifest, themes


def check(slug):
    out = TALKS / slug / "build" / "web"
    index = out / "index.html"
    if not index.is_file():
        fail(f"no build: run python3 scripts/to_web.py {slug}")
    html = index.read_text()
    problems = []
    if re.search(r"\{\{[A-Z_]+\}\}", html):
        problems.append("unreplaced {{PLACEHOLDER}} in index.html")
    for hit in re.findall(r"(?:src|href)=\"https?://[^\"]*\"|<script[^>]+src=|<link[^>]+stylesheet|@import|url\(\s*[\"']?https?:", html):
        problems.append(f"external dependency: {hit}")
    data = json.loads(re.search(r'<script type="application/json" id="talk-data">(.*?)</script>', html, re.S).group(1).replace("<\\/", "</"))
    ids = [f["id"] for f in data["frames"]]
    if len(ids) != len(set(ids)):
        problems.append("duplicate slide ids")
    for theme in data["themes"]:
        for f in data["frames"]:
            for p in f["pages"]:
                svg = out / "slides" / theme / f"{p:03d}.svg"
                if not svg.is_file() or svg.stat().st_size < 200:
                    problems.append(f"{f['id']}: missing or empty slides/{theme}/{p:03d}.svg")
    notes = (out / "notes.md").read_text() if (out / "notes.md").is_file() else ""
    sections = re.findall(r"^## (\S+)$", notes, re.M)
    if sections[1:] != ids:
        problems.append("notes.md sections do not match the slide ids in order")
    for f in data["frames"]:
        if f["kind"] == "frame" and not f["title"]:
            problems.append(f"{f['id']}: frame without a title")
    total = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    if total > MAX_DECK_BYTES:
        problems.append(f"deck is {total / 1e6:.1f} MB (> {MAX_DECK_BYTES / 1e6:.0f} MB)")
    if problems:
        fail("check failed:\n  " + "\n  ".join(problems))
    digest = hashlib.sha256()
    for p in sorted(out.rglob("*")):
        if p.is_file():
            digest.update(p.relative_to(out).as_posix().encode() + p.read_bytes())
    print(f"verified: {slug} web deck, {len(ids)} slides, {len(data['themes'])} themes, "
          f"{total / 1e6:.1f} MB, no external dependencies, tree sha256 {digest.hexdigest()[:12]}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("slug")
    ap.add_argument("--check", action="store_true", help="verify an existing build; write nothing")
    args = ap.parse_args()
    if args.check:
        check(args.slug)
        return
    out, manifest, themes = build(args.slug)
    print(f"wrote {out.relative_to(ROOT)}: {len(manifest['frames'])} slides, {manifest['pages']} pages, "
          f"themes {', '.join(themes)}; serve with: python3 -m http.server -d {out.relative_to(ROOT)}")
    check(args.slug)


if __name__ == "__main__":
    main()
