#!/usr/bin/env python3
"""Derive the chart data and headline numbers for the Breeden-Litzenberger talk.

Input is data/raw.json and data/meta.json, a snapshot of the visuals repo's
data/breeden-litzenberger-density/. `--sync VISUALS_DIR` refreshes the
snapshot. Output is data/curves.csv, data/butterflies.csv and data/numbers.tex;
the talk reads every number from these files, never by hand. `--verify`
recomputes everything, checks it against the visuals page's asserted values,
and fails if a committed output is stale. It writes nothing.

All prices are synthetic Black-Scholes prices, not market data.
"""
import argparse
import json
import math
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
SLUG = "breeden-litzenberger-density"

# Illustrative quote error per option price (one cent), used only for the
# noise-versus-bias slide. It is an assumption of this talk, not visuals data.
EPSILON = 0.01


def Phi(x):
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def phi(x):
    return math.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def bs_call(K, S0, r, sig, T):
    d1 = (math.log(S0 / K) + (r + 0.5 * sig * sig) * T) / (sig * math.sqrt(T))
    d2 = d1 - sig * math.sqrt(T)
    return S0 * Phi(d1) - K * math.exp(-r * T) * Phi(d2)


def density(K, S0, r, sig, T):
    d2 = (math.log(S0 / K) + (r - 0.5 * sig * sig) * T) / (sig * math.sqrt(T))
    return phi(d2) / (K * sig * math.sqrt(T))


def derive(raw):
    m = raw["model"]
    S0, r, sig, T = m["S0"], m["r"], m["sigma"], m["T"]
    g = raw["grid"]
    erT = math.exp(r * T)
    n = round((g["K_max"] - g["K_min"]) / g["step"]) + 1
    strikes = [g["K_min"] + i * g["step"] for i in range(n)]
    calls = [bs_call(k, S0, r, sig, T) for k in strikes]
    h = g["step"]

    curves = ["K,call,density,fd"]
    for i, k in enumerate(strikes):
        if 0 < i < n - 1:
            fd = f"{erT * (calls[i - 1] - 2 * calls[i] + calls[i + 1]) / (h * h):.6f}"
        else:
            fd = "nan"
        curves.append(f"{k:.1f},{calls[i]:.6f},{density(k, S0, r, sig, T):.6f},{fd}")

    K0 = raw["reference_strike"]
    C0 = bs_call(K0, S0, r, sig, T)
    p0 = density(K0, S0, r, sig, T)
    rows, flies = ["delta,price,estimate,bias,noise"], []
    for d in raw["butterfly_half_widths"]:
        price = bs_call(K0 - d, S0, r, sig, T) - 2 * C0 + bs_call(K0 + d, S0, r, sig, T)
        est = erT * price / (d * d)
        noise = erT * 4 * EPSILON / (d * d)
        flies.append((d, price, est, abs(est - p0), noise))
        rows.append(f"{d:.1f},{price:.6f},{est:.6f},{abs(est - p0):.6f},{noise:.6f}")

    numbers = {
        "blSzero": f"{S0:g}",
        "blRate": f"{r * 100:g}\\%",
        "blSigma": f"{sig * 100:g}\\%",
        "blT": f"{T:g}",
        "blKzero": f"{K0:g}",
        "blErT": f"{erT:.4f}",
        "blCzero": f"{C0:.4f}",
        "blPzero": f"{p0:.6f}",
        "blCpp": f"{math.exp(-r * T) * p0:.6f}",
        "blEps": f"{EPSILON:g}",
        "blDeltaMin": f"{flies[-1][0]:g}",
        "blEstMin": f"{flies[-1][2]:.6f}",
        "blNoiseMin": f"{flies[-1][4]:.4f}",
        "blNoiseRatio": f"{flies[-1][4] / p0:.0f}",
        "blStrikes": f"{n}",
    }
    tex = ["% Generated by derive.py from data/raw.json. Do not edit."]
    tex += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in numbers.items()]
    outputs = {
        "curves.csv": "\n".join(curves) + "\n",
        "butterflies.csv": "\n".join(rows) + "\n",
        "numbers.tex": "\n".join(tex) + "\n",
    }
    return outputs, {"p0": p0, "C0": C0, "flies": flies, "calls": calls}


def check(raw, meta, model):
    # The same terminal results the visuals page asserts.
    assert raw["model"] == {"S0": 100.0, "r": 0.05, "sigma": 0.20, "T": 1.0}
    assert meta["slug"] == SLUG
    assert round(model["p0"], 6) == 0.019724
    assert round(model["C0"], 4) == 10.4506
    by = {f[0]: f[2] for f in model["flies"]}
    assert [round(by[d], 6) for d in (5.0, 2.0, 1.0, 0.5)] == [0.019623, 0.019708, 0.019720, 0.019723]
    calls = model["calls"]
    assert all(a > b for a, b in zip(calls, calls[1:])), "call price must fall with strike"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sync", metavar="VISUALS_DIR", help="refresh data/raw.json and meta.json from visuals")
    ap.add_argument("--verify", action="store_true", help="check outputs are current; write nothing")
    args = ap.parse_args()

    if args.sync:
        src = Path(args.sync) / "data" / SLUG
        for name in ("raw.json", "meta.json"):
            shutil.copyfile(src / name, DATA / name)
        print(f"synced data/raw.json and data/meta.json from visuals/data/{SLUG}")

    raw = json.loads((DATA / "raw.json").read_text())
    meta = json.loads((DATA / "meta.json").read_text())
    outputs, model = derive(raw)
    check(raw, meta, model)

    stale = [n for n, t in outputs.items() if not (DATA / n).is_file() or (DATA / n).read_text() != t]
    if args.verify:
        if stale:
            sys.exit(f"stale: {', '.join(stale)}; run python3 {Path(__file__).name}")
        print(f"verified: density {model['p0']:.6f}, {len(outputs)} outputs current")
        return
    for name, text in outputs.items():
        (DATA / name).write_text(text)
    print(f"wrote {', '.join(outputs)}; density at K0 = {model['p0']:.6f}")


if __name__ == "__main__":
    main()
